#!/usr/bin/env python3
"""
Regenerate the <link rel="modulepreload"> block in index.html.

The app is deliberately buildless: index.html loads js/app.js as a
single ES module and the browser walks the static import graph from
there. That graph is 108 modules deep in FOUR layers, and the browser
can only discover each layer after downloading and parsing the one
above it — so a cold load spends three extra round-trips just learning
what to fetch, before any of it can run. On a phone that is most of a
second of nothing.

modulepreload collapses it: the browser is told the whole set up front
and fetches it in one parallel wave. It is a hint only — a stale or
missing entry costs a console warning, never a failure — which is what
makes it the right tool for a project with no bundler.

The block is emitted AFTER the stylesheet links on purpose. Chrome
gives module preloads high priority, and CSS is render-blocking;
queueing it first keeps the preloads from delaying first paint.

Rerun after adding or removing modules:
    python3 tools/gen-modulepreload.py
"""

import collections
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ENTRY = ROOT / 'js' / 'app.js'
INDEX = ROOT / 'index.html'

BEGIN = '    <!-- BEGIN modulepreload (generated by tools/gen-modulepreload.py) -->'
END   = '    <!-- END modulepreload -->'

IMPORT = re.compile(r"""^\s*import\s+(?:[^'"]*?from\s+)?['"](\.[^'"]+)['"]""", re.M)


def dependencies(path):
    try:
        src = path.read_text()
    except OSError:
        return []
    out = []
    for m in IMPORT.finditer(src):
        target = (path.parent / m.group(1)).resolve()
        if target.exists():
            out.append(target)
    return out


def walk(entry):
    """Breadth-first over the static import graph. Returns {path: depth}."""
    depth = {entry: 0}
    queue = collections.deque([entry])
    while queue:
        cur = queue.popleft()
        for dep in dependencies(cur):
            if dep not in depth:
                depth[dep] = depth[cur] + 1
                queue.append(dep)
    return depth


def main():
    depth = walk(ENTRY)
    # app.js itself is already referenced by the <script> tag — preloading
    # it as well would just be a duplicate request hint.
    modules = sorted(
        (p for p in depth if p != ENTRY),
        key=lambda p: (depth[p], str(p)),
    )

    lines = [BEGIN]
    for p in modules:
        rel = p.relative_to(ROOT).as_posix()
        lines.append(f'    <link rel="modulepreload" href="/{rel}" />')
    lines.append(END)
    block = '\n'.join(lines)

    html = INDEX.read_text()
    if BEGIN in html and END in html:
        start = html.index(BEGIN)
        stop = html.index(END) + len(END)
        html = html[:start] + block + html[stop:]
    else:
        anchor = '  </head>'
        if anchor not in html:
            print('could not find </head> in index.html', file=sys.stderr)
            return 1
        html = html.replace(anchor, block + '\n' + anchor, 1)

    INDEX.write_text(html)

    levels = collections.Counter(depth.values())
    print(f'{len(modules)} modules preloaded '
          f'(graph depth {max(depth.values()) + 1} → 1 fetch wave)')
    for lvl in sorted(levels):
        print(f'  level {lvl}: {levels[lvl]:>3}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
